# Generated by Django 5.2.11 on 2026-05-21 11:11

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='id',
            field=models.CharField(default=administration.models.generate_designation_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
