# Generated by Django 5.2.11 on 2026-05-27 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_designation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('REACTIVATION_REQUEST', 'Reactivation Request'), ('DESIGNATION_CHANGE_REQUEST', 'Designation Change Request'), ('USER_BLOCKED', 'User Blocked'), ('USER_UNBLOCKED', 'User Unblocked'), ('USER_DELETED', 'User Deleted'), ('USER_RESTORED', 'User Restored'), ('NEW_USER_RESOLVED', 'New User Request Resolved'), ('DESIGNATION_CHANGE_RESOLVED', 'Designation Change Request Resolved'), ('REACTIVATION_RESOLVED', 'Reactivation Request Resolved')], max_length=50)),
                ('action_details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_admin_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
