"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import pymysql
pymysql.install_as_MySQLdb()
import os
from dotenv import load_dotenv
from pathlib import Path
from pythonjsonlogger import jsonlogger


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG", "False") == "True"
ALLOWED_HOSTS = [
    ".onrender.com"
]
CORS_ALLOWED_ORIGINS = [
    "https://inv-rr-git-deploy-render-hosting-abhiram-s-projects4.vercel.app",
    "https://hivedrive.vercel.app"
]
CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_SAMESITE = "None"  
CSRF_COOKIE_SAMESITE ="None" 
AUTH_COOKIE_SAMESITE ="None"
SESSION_COOKIE_SECURE = True     # True in production (HTTPS)
CSRF_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = [
    "https://inv-rr-git-deploy-render-hosting-abhiram-s-projects4.vercel.app",
    "https://hivedrive.vercel.app"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'files',
    'administration',
    'rest_framework',
    "corsheaders",
]

MIDDLEWARE = [
      "corsheaders.middleware.CorsMiddleware",  
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'
AUTH_USER_MODEL='files.User'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get("DATABASE_URL")
    )
}



STORAGES = {
    "default": {
        "BACKEND": "files.supabase_storage.SupabaseStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


PASSWORD_RESET_TIMEOUT = int(os.getenv("PASSWORD_RESET_TIMEOUT", 300))

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE='Asia/Kolkata'
USE_TZ = True

USE_I18N = True
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "files.authentication.CookieJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "files.permissions.IsActiveAccount",
    ),
}
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

AUTH_COOKIE_ACCESS = "access_token"
AUTH_COOKIE_REFRESH = "refresh_token"
AUTH_COOKIE_SECURE = not DEBUG
AUTH_COOKIE_HTTP_ONLY = True

BREVO_API_KEY = os.getenv("BREVO_API_KEY")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")


EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"
ANYMAIL = {
    "BREVO_API_KEY": BREVO_API_KEY,
}

BACKEND_BASE_URL = os.getenv("BACKEND_BASE_URL")
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL") 
LOGS_DIR = BASE_DIR / "logs"
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            "datefmt": "%d/%b/%Y %H:%M:%S"
        },
    },

    "handlers": {
        "general_file": {
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "general.log",
            "formatter": "standard",
        },
        "server_file": {
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "server.log",
            "formatter": "standard",
        },
        "files_file": {
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "files.log",
            "formatter": "standard",
        },
        "users_file": {
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "users.log",
            "formatter": "standard",
        },
        
    },

    "loggers": {
        "": {
            "handlers": ["general_file"],
            "level": "INFO",
        },
        "django.server": {
            "handlers": ["server_file"],
            "level": "INFO",
            "propagate": False,
        },
        "files": {
            "handlers": ["files_file"],
            "level": "INFO",
            "propagate": False,
        },
        "users": {
            "handlers": ["users_file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.utils.autoreload": {
            "handlers": ["general_file"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

import ssl
from celery.schedules import crontab

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = CELERY_BROKER_URL

CELERY_BROKER_USE_SSL = {
    "ssl_cert_reqs": ssl.CERT_NONE
}

CELERY_REDIS_BACKEND_USE_SSL = {
    "ssl_cert_reqs": ssl.CERT_NONE
}
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True



CELERY_BEAT_SCHEDULE = {
    "auto-clear-trash": {
        "task": "files.tasks.auto_clear_trash",
        # Runs daily at midnight
        "schedule": crontab(minute=0, hour=0),
    },

    "auto-clear-scheduled-mails-history": {
        "task": "files.tasks.auto_clear_scheduled_mails_history",
        # Runs daily at 00:30
        "schedule": crontab(minute=30, hour=0),
    },

    "auto-generate-monthly-reports": {
        "task": "files.tasks.auto_generate_report",
        "schedule": crontab(minute=0, hour=0, day_of_month=1)
    },
    "auto-delete-users": {
        "task": "files.tasks.auto_delete_users",
        "schedule": crontab(minute=0, hour=1), 
    },
    'auto-clear-old-admin-logs': {
        'task': 'files.tasks.auto_clear_old_admin_logs',
        "schedule": crontab(minute=30, hour=1),
    },
    "auto-delete-deactivated-users": {
        "task": "files.tasks.auto_delete_deactivated_users",
         "schedule": crontab(minute=0, hour=2),
    }
}

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
SUPABASE_BUCKET = os.getenv("SUPABASE_BUCKET")
