# Generated by Django 6.0.2 on 2026-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
