# Generated by Django 5.2.11 on 2026-02-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_filesharelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesharelink',
            name='expiration_datetime',
            field=models.DateTimeField(),
        ),
    ]
