# Generated by Django 5.2.11 on 2026-02-18 09:28

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_filesharelink_expiration_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=files.models.default_expiry),
        ),
    ]
