# Generated by Django 5.2.11 on 2026-02-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_file_deleted_at_file_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesharelink',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
