# Generated by Django 5.2.11 on 2026-03-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_filesharelink_revoked_at_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
