# Generated by Django 5.2.11 on 2026-03-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_file_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
