# Generated by Django 5.2.11 on 2026-04-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_collection_collectionfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionfile',
            name='note',
        ),
    ]
