# Generated by Django 5.2.11 on 2026-04-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_remove_collectionfile_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filesharelink',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='collection',
            table='collections',
        ),
        migrations.AlterModelTable(
            name='collectionfile',
            table='collection_files',
        ),
        migrations.AlterModelTable(
            name='file',
            table='files',
        ),
        migrations.AlterModelTable(
            name='filesharelink',
            table='file_share_links',
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_users',
        ),
    ]
