# Generated by Django 5.2.11 on 2026-04-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_alter_filesharelink_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
