# Generated by Django 5.2.11 on 2026-04-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_role_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
