# Generated by Django 5.2.11 on 2026-04-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0017_remove_user_role_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('resource', 'Resource')], default='resource', max_length=20),
        ),
    ]
