# Generated by Django 5.2.11 on 2026-04-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0019_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Resource', 'Resource')], default='Resource', max_length=20),
        ),
    ]
