# Generated by Django 5.2.11 on 2026-04-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0020_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('project_manager', 'Project Manager'), ('team_manager', 'Team Manager'), ('delivery_manager', 'Delivery Manager'), ('product_manager', 'Product Manager'), ('operations_manager', 'Operations Manager')], default='project_manager', max_length=20),
        ),
    ]
