# Generated by Django 5.2.11 on 2026-04-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0023_scheduledmail_title_alter_scheduledmail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('project_manager', 'Project Manager'), ('team_lead', 'Team Lead'), ('delivery_manager', 'Delivery Manager'), ('product_manager', 'Product Manager'), ('operations_manager', 'Operations Manager'), ('program_manager', 'Program Manager')], default='project_manager', max_length=20),
        ),
    ]
