# Generated by Django 5.2.11 on 2026-04-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0024_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='designation',
        ),
    ]
