# Generated by Django 5.2.11 on 2026-04-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0025_rename_role_user_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='storage_limit_bytes',
            field=models.BigIntegerField(default=1073741824),
        ),
        migrations.AddField(
            model_name='user',
            name='storage_used_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
