# Generated by Django 5.2.11 on 2026-04-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0026_user_storage_limit_bytes_user_storage_used_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='storage_limit_bytes',
            field=models.BigIntegerField(default=10485760),
        ),
    ]
