# Generated by Django 5.2.11 on 2026-05-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0028_alter_user_storage_limit_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
    ]
