# Generated by Django 5.2.11 on 2026-05-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0029_alter_scheduledmail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
