# Generated by Django 5.2.11 on 2026-05-07 04:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0030_file_archived_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='file',
            name='last_accessed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
