# Generated by Django 5.2.11 on 2026-05-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0032_projectnode_nodefile_nodeactivity_projectthread_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectnode',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='projectnode',
            name='position_y',
        ),
        migrations.AddField(
            model_name='projectnode',
            name='row',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectnode',
            name='stage',
            field=models.IntegerField(default=0),
        ),
    ]
