# Generated by Django 5.2.11 on 2026-05-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0033_remove_projectnode_position_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodedependency',
            name='dependency_type',
            field=models.CharField(choices=[('REQUIRED_FOR', 'Required For'), ('NEXT_STAGE', 'Next Stage')], default='REQUIRED_FOR', max_length=20),
        ),
    ]
