# Generated by Django 5.2.11 on 2026-05-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0034_alter_nodedependency_dependency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodedependency',
            name='dependency_type',
            field=models.CharField(choices=[('DEPENDS_ON', 'Depends On')], default='DEPENDS_ON', max_length=20),
        ),
    ]
