# Generated by Django 5.2.11 on 2026-05-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0035_alter_nodedependency_dependency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodedependency',
            name='dependency_type',
            field=models.CharField(choices=[('DEPENDS_ON', 'Depends On'), ('REQUIRED_FOR', 'Required For'), ('WAITING_FOR', 'Waiting For'), ('RELATED', 'Related'), ('NOT_SURE', 'Not Sure'), ('NEEDS_REVIEW', 'Needs Review')], default='DEPENDS_ON', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectnode',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('NEEDS_REVIEW', 'Needs Review'), ('OUTDATED', 'Outdated'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived')], default='INACTIVE', max_length=20),
        ),
    ]
