# Generated by Django 5.2.11 on 2026-05-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0038_alter_user_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('Waiting For Approval', 'Waiting For Approval'), ('active', 'Active'), ('deactivated', 'Deactivated'), ('blocked', 'Blocked'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
    ]
