# Generated by Django 5.2.11 on 2026-05-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0041_projectstage_alter_projectnode_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesharelink',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filesharelink',
            name='download_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filesharelink',
            name='permission',
            field=models.CharField(choices=[('view_only', 'View Only'), ('view_download', 'View + Download'), ('one_time_download', 'One-time Download'), ('full_access', 'Full Access')], default='view_only', max_length=20),
        ),
    ]
