# Generated by Django 5.2.11 on 2026-05-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0042_filesharelink_download_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesharelink',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filesharelink',
            name='view_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
