# Generated by Django 5.2.11 on 2026-05-21 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0043_filesharelink_view_count_filesharelink_view_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_designation', models.CharField(choices=[('project_manager', 'Project Manager'), ('team_lead', 'Team Lead'), ('delivery_manager', 'Delivery Manager'), ('product_manager', 'Product Manager'), ('operations_manager', 'Operations Manager'), ('program_manager', 'Program Manager')], max_length=20)),
                ('requested_designation', models.CharField(choices=[('project_manager', 'Project Manager'), ('team_lead', 'Team Lead'), ('delivery_manager', 'Delivery Manager'), ('product_manager', 'Product Manager'), ('operations_manager', 'Operations Manager'), ('program_manager', 'Program Manager')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'designation_change_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
