# Generated by Django 5.2.11 on 2026-05-21 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0044_designationchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='designationchangerequest',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='designationchangerequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_designation_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
