# Generated by Django 5.2.11 on 2026-05-22 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0045_designationchangerequest_admin_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True)),
                ('permission', models.CharField(choices=[('view_only', 'View Only'), ('view_download', 'View + Download'), ('one_time_download', 'One Time Download'), ('full_access', 'Full Access')], default='view_only', max_length=30)),
                ('expiration_datetime', models.DateTimeField()),
                ('download_limit', models.IntegerField(blank=True, null=True)),
                ('view_limit', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BundleRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('accessed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='files.sharebundle')),
            ],
        ),
        migrations.CreateModel(
            name='ShareBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='files.sharebundle')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.file')),
            ],
        ),
    ]
