# Generated by Django 5.2.11 on 2026-05-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0046_sharebundle_bundlerecipient_sharebundleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharebundle',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharebundle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sharebundle',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharebundle',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='share_bundles/'),
        ),
    ]
