# Generated by Django 5.2.11 on 2026-05-22 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0047_sharebundle_download_count_sharebundle_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesharelink',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='files.sharebundle'),
        ),
    ]
