# Generated by Django 5.2.11 on 2026-05-25 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0050_designation_foreign_keys'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chunkuploadsession',
            new_name='chunk_uploa_user_id_95f623_idx',
            old_name='chunk_upl_user_id_8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='chunkuploadsession',
            new_name='chunk_uploa_expires_b7c667_idx',
            old_name='chunk_upl_expires_4c9e1a_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_report_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filesharelink',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='files.file'),
        ),
    ]
