# Generated by Django 5.2.11 on 2026-05-26 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0051_rename_chunk_upl_user_id_8a1f2d_idx_chunk_uploa_user_id_95f623_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodefile',
            name='vault_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.file'),
        ),
    ]
