# Generated by Django 5.2.11 on 2026-05-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0052_nodefile_vault_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodefile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TRASHED', 'Trashed')], default='ACTIVE', max_length=20),
        ),
    ]
