# Generated by Django 5.2.11 on 2026-05-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0053_nodefile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodefile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('TRASHED', 'Trashed')], default='ACTIVE', max_length=20),
        ),
    ]
