# Generated by Django 5.2.11 on 2026-05-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0054_alter_nodefile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionfile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('TRASHED', 'Trashed')], default='ACTIVE', max_length=20),
        ),
    ]
