# Generated by Django 5.2.11 on 2026-05-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0055_collectionfile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectnode',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('NEEDS_REVIEW', 'Needs Review'), ('OUTDATED', 'Outdated'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed')], default='INACTIVE', max_length=20),
        ),
    ]
