# Generated by Django 5.2.11 on 2026-05-29 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0056_alter_projectnode_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesharelink',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='files.file'),
        ),
    ]
