# Generated by Django 5.2.11 on 2026-06-01 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0059_user_deactivated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bundlerecipient',
            table='bundle_recipients',
        ),
        migrations.AlterModelTable(
            name='nodeactivity',
            table='node_activities',
        ),
        migrations.AlterModelTable(
            name='nodedependency',
            table='node_dependencies',
        ),
        migrations.AlterModelTable(
            name='nodefile',
            table='node_files',
        ),
        migrations.AlterModelTable(
            name='projectnode',
            table='project_nodes',
        ),
        migrations.AlterModelTable(
            name='projectstage',
            table='project_stages',
        ),
        migrations.AlterModelTable(
            name='projectthread',
            table='project_threads',
        ),
        migrations.AlterModelTable(
            name='sharebundle',
            table='share_bundles',
        ),
        migrations.AlterModelTable(
            name='sharebundleitem',
            table='share_bundle_items',
        ),
    ]
